name: invoify
description: "Invoify - Automated invoicing and payment tracking mobile application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  gap: ^3.0.1
  toastification: ^3.2.0

  # State Management & Architecture
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0

  # Local Services & Preferences
  shared_preferences: ^2.5.5

  # Localization
  easy_localization: ^3.0.8

  # Utilities & Logging
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/svgs/icons/
    - assets/translations/

# Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.jpg"


# Native Splash Screen Configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app-icon.jpg
  color_dark: "#0F172A"
  image_dark: assets/images/app-icon.jpg

  android_12:
    image: assets/images/splash_ios_android_12.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/splash_android_12_dark.png
    icon_background_color_dark: "#0F172A"
