import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:gap/gap.dart';
import 'package:invoify/core/helpers/app_strings.dart';
import 'package:invoify/core/helpers/di.dart';
import 'package:invoify/core/helpers/extensions.dart';
import 'package:invoify/core/widgets/app_toasts.dart';
import 'package:invoify/core/widgets/custom_app_bar.dart';
import 'package:invoify/core/widgets/custom_keyboard_unfocus.dart';
import 'package:invoify/core/widgets/text_form_field_helper.dart';
import 'package:invoify/features/clients/domain/entities/client_entity.dart';
import 'package:invoify/features/clients/presentation/view_models/clients_cubit/clients_cubit.dart';
import 'package:invoify/features/invoices/domain/entities/invoice_entity.dart';
import 'package:invoify/features/invoices/domain/entities/invoice_item_entity.dart';
import 'package:invoify/features/invoices/domain/enums/discount_type.dart';
import 'package:invoify/features/invoices/presentation/view_models/invoices_cubit/invoices_cubit.dart';
import 'package:invoify/features/invoices/presentation/view_models/invoices_cubit/invoices_state.dart';
import 'package:invoify/features/invoices/presentation/widgets/add_edit_invoice_save_button.dart';
import 'package:invoify/features/invoices/presentation/widgets/invoice_badge_number.dart';
import 'package:invoify/features/invoices/presentation/widgets/invoice_calculation_summary.dart';
import 'package:invoify/features/invoices/presentation/widgets/invoice_client_picker.dart';
import 'package:invoify/features/invoices/presentation/widgets/invoice_dates_section.dart';
import 'package:invoify/features/invoices/presentation/widgets/invoice_items_section.dart';
import 'package:toastification/toastification.dart';

class AddEditInvoiceView extends StatefulWidget {
  const AddEditInvoiceView({super.key, this.invoice});

  final InvoiceEntity? invoice;

  @override
  State<AddEditInvoiceView> createState() => _AddEditInvoiceViewState();
}

class _AddEditInvoiceViewState extends State<AddEditInvoiceView> {
  final _formKey = GlobalKey<FormState>();

  late final ValueNotifier<ClientEntity?> _selectedClientNotifier;
  late final ValueNotifier<DateTime> _issueDateNotifier;
  late final ValueNotifier<DateTime> _dueDateNotifier;
  late final ValueNotifier<List<InvoiceItemEntity>> _itemsNotifier;
  late final ValueNotifier<DiscountType> _discountTypeNotifier;
  final ValueNotifier<bool> _isLoadingNotifier = ValueNotifier<bool>(false);
  late TextEditingController _taxRateController;
  late TextEditingController _discountController;
  late TextEditingController _notesController;
  late String _autoGeneratedInvoiceNumber;

  bool get _isEditing => widget.invoice != null;

  @override
  void initState() {
    super.initState();
    _selectedClientNotifier = ValueNotifier<ClientEntity?>(
      widget.invoice?.client,
    );
    _issueDateNotifier = ValueNotifier<DateTime>(
      widget.invoice?.issueDate ?? DateTime.now(),
    );
    _dueDateNotifier = ValueNotifier<DateTime>(
      widget.invoice?.dueDate ?? DateTime.now().add(const Duration(days: 14)),
    );
    _itemsNotifier = ValueNotifier<List<InvoiceItemEntity>>(
      widget.invoice?.items.isNotEmpty == true
          ? widget.invoice!.items
          : [
              const InvoiceItemEntity(
                itemId: '1',
                name: '',
                quantity: 1,
                unitPrice: 0,
              ),
            ],
    );

    _discountTypeNotifier = ValueNotifier<DiscountType>(
      widget.invoice?.discountType ?? DiscountType.percentage,
    );

    _taxRateController = TextEditingController(
      text: (widget.invoice != null && widget.invoice!.taxRate > 0)
          ? widget.invoice!.taxRate.toString()
          : '',
    );
    _discountController = TextEditingController(
      text: widget.invoice != null
          ? (_discountTypeNotifier.value.isPercentage
                ? (widget.invoice!.discountRate > 0
                      ? widget.invoice!.discountRate.toString()
                      : '')
                : (widget.invoice!.discountAmount > 0
                      ? widget.invoice!.discountAmount.toString()
                      : ''))
          : '',
    );
    _notesController = TextEditingController(text: widget.invoice?.notes ?? '');

    if (_isEditing) {
      _autoGeneratedInvoiceNumber = widget.invoice!.invoiceNumber;
    } else {
      final now = DateTime.now();
      final dateStr =
          '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}';
      final suffix = (now.millisecondsSinceEpoch % 10000).toString().padLeft(
        4,
        '0',
      );
      _autoGeneratedInvoiceNumber = 'INV-$dateStr-$suffix';
    }
  }

  @override
  void dispose() {
    _selectedClientNotifier.dispose();
    _issueDateNotifier.dispose();
    _dueDateNotifier.dispose();
    _itemsNotifier.dispose();
    _discountTypeNotifier.dispose();
    _isLoadingNotifier.dispose();
    _taxRateController.dispose();
    _discountController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;

    return BlocProvider(
      create: (context) => getIt<ClientsCubit>(),
      child: CustomKeyboardUnfocus(
        child: Scaffold(
          appBar: CustomAppBar(
            title: _isEditing
                ? AppStrings.editInvoice
                : AppStrings.createInvoice,
            showArrowBack: true,
          ),
          body: SafeArea(
            child: BlocConsumer<InvoicesCubit, InvoicesState>(
              listener: (context, state) {
                if (state is InvoiceActionSuccess) {
                  _isLoadingNotifier.value = false;
                  AppToast.show(
                    context: context,
                    title: state.message,
                    type: ToastificationType.success,
                  );
                  context.pop(true);
                } else if (state is InvoicesFailure) {
                  _isLoadingNotifier.value = false;
                  AppToast.show(
                    context: context,
                    title: state.error,
                    type: ToastificationType.error,
                  );
                }
              },
              builder: (context, state) => SingleChildScrollView(
                padding: EdgeInsets.symmetric(horizontal: 16.w, vertical: 16.h),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Invoice Number Badge
                      InvoiceNumberBadge(
                        autoGeneratedInvoiceNumber: _autoGeneratedInvoiceNumber,
                      ),
                      Gap(16.h),

                      // Client Picker Section
                      ValueListenableBuilder<ClientEntity?>(
                        valueListenable: _selectedClientNotifier,
                        builder: (context, selectedClient, child) =>
                            InvoiceClientPicker(
                              selectedClient: selectedClient,
                              onClientSelected: (client) {
                                _selectedClientNotifier.value = client;
                              },
                            ),
                      ),
                      Gap(16.h),

                      // Dates Section (Issue & Due Date)
                      InvoiceDatesSection(
                        issueDateNotifier: _issueDateNotifier,
                        dueDateNotifier: _dueDateNotifier,
                      ),
                      Gap(20.h),

                      // Invoice Items Section
                      ValueListenableBuilder<List<InvoiceItemEntity>>(
                        valueListenable: _itemsNotifier,
                        builder: (context, items, child) => InvoiceItemsSection(
                          items: items,
                          onAddItem: () {
                            final current = List<InvoiceItemEntity>.from(items);
                            current.add(
                              InvoiceItemEntity(
                                itemId: DateTime.now().millisecondsSinceEpoch
                                    .toString(),
                                name: '',
                                quantity: 1,
                                unitPrice: 0,
                              ),
                            );
                            _itemsNotifier.value = current;
                          },
                          onRemoveItem: (index) {
                            final current = List<InvoiceItemEntity>.from(items);
                            current.removeAt(index);
                            _itemsNotifier.value = current;
                          },
                          onUpdateItem: (index, updatedItem) {
                            final current = List<InvoiceItemEntity>.from(items);
                            current[index] = updatedItem;
                            _itemsNotifier.value = current;
                          },
                        ),
                      ),
                      Gap(20.h),

                      // Dynamic Calculations Summary
                      ValueListenableBuilder<List<InvoiceItemEntity>>(
                        valueListenable: _itemsNotifier,
                        builder: (context, items, child) {
                          final subtotal = items.fold(
                            0.0,
                            (sum, item) => sum + item.totalPrice,
                          );

                          return InvoiceCalculationSummary(
                            subtotal: subtotal,
                            taxRateController: _taxRateController,
                            discountController: _discountController,
                            discountTypeNotifier: _discountTypeNotifier,
                          );
                        },
                      ),
                      Gap(20.h),

                      // Optional Notes Section
                      TextFormFieldHelper(
                        controller: _notesController,
                        hint: AppStrings.notesHint,
                        maxLines: 3,
                        prefixIcon: Icon(
                          Icons.note_alt_outlined,
                          color: colors.subText,
                          size: 20.sp,
                        ),
                      ),
                      Gap(28.h),

                      // Save Button
                      AddEditInvoiceSaveButton(
                        existingInvoice: widget.invoice,
                        isEditing: _isEditing,
                        autoGeneratedInvoiceNumber: _autoGeneratedInvoiceNumber,
                        selectedClientNotifier: _selectedClientNotifier,
                        itemsNotifier: _itemsNotifier,
                        issueDateNotifier: _issueDateNotifier,
                        dueDateNotifier: _dueDateNotifier,
                        taxRateController: _taxRateController,
                        discountController: _discountController,
                        discountTypeNotifier: _discountTypeNotifier,
                        notesController: _notesController,
                        isLoadingNotifier: _isLoadingNotifier,
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
