import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:gap/gap.dart';
import 'package:invoify/core/helpers/app_strings.dart';
import 'package:invoify/core/helpers/di.dart';
import 'package:invoify/core/helpers/extensions.dart';
import 'package:invoify/core/theming/app_text_styles.dart';
import 'package:invoify/core/widgets/app_toasts.dart';
import 'package:invoify/core/widgets/custom_app_bar.dart';
import 'package:invoify/core/widgets/custom_keyboard_unfocus.dart';
import 'package:invoify/core/widgets/custom_material_button.dart';
import 'package:invoify/core/widgets/text_form_field_helper.dart';
import 'package:invoify/features/clients/domain/entities/client_entity.dart';
import 'package:invoify/features/clients/presentation/view_models/clients_cubit/clients_cubit.dart';
import 'package:invoify/features/invoices/domain/entities/invoice_entity.dart';
import 'package:invoify/features/invoices/domain/entities/invoice_item_entity.dart';
import 'package:invoify/features/invoices/domain/enums/invoice_status.dart';
import 'package:invoify/features/invoices/presentation/view_models/invoices_cubit/invoices_cubit.dart';
import 'package:invoify/features/invoices/presentation/view_models/invoices_cubit/invoices_state.dart';
import 'package:invoify/features/invoices/presentation/widgets/invoice_calculation_summary.dart';
import 'package:invoify/features/invoices/presentation/widgets/invoice_client_picker.dart';
import 'package:invoify/features/invoices/presentation/widgets/invoice_dates_section.dart';
import 'package:invoify/features/invoices/presentation/widgets/invoice_items_section.dart';
import 'package:toastification/toastification.dart';

class CreateInvoiceView extends StatefulWidget {
  const CreateInvoiceView({super.key});

  @override
  State<CreateInvoiceView> createState() => _CreateInvoiceViewState();
}

class _CreateInvoiceViewState extends State<CreateInvoiceView> {
  final _formKey = GlobalKey<FormState>();

  final ValueNotifier<ClientEntity?> _selectedClientNotifier =
      ValueNotifier<ClientEntity?>(null);
  final ValueNotifier<DateTime> _issueDateNotifier = ValueNotifier<DateTime>(
    DateTime.now(),
  );
  final ValueNotifier<DateTime> _dueDateNotifier = ValueNotifier<DateTime>(
    DateTime.now().add(const Duration(days: 14)),
  );
  final ValueNotifier<List<InvoiceItemEntity>> _itemsNotifier =
      ValueNotifier<List<InvoiceItemEntity>>([
        const InvoiceItemEntity(
          itemId: '1',
          name: '',
          quantity: 1,
          unitPrice: 0,
        ),
      ]);
  final ValueNotifier<bool> _isLoadingNotifier = ValueNotifier<bool>(false);
  late TextEditingController _taxRateController;
  late TextEditingController _discountController;
  late TextEditingController _notesController;
  late String _autoGeneratedInvoiceNumber;

  @override
  void initState() {
    super.initState();
    _taxRateController = TextEditingController();
    _discountController = TextEditingController();
    _notesController = TextEditingController();

    final now = DateTime.now();
    final dateStr =
        '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}';
    final suffix = (now.millisecondsSinceEpoch % 10000).toString().padLeft(
      4,
      '0',
    );
    _autoGeneratedInvoiceNumber = 'INV-$dateStr-$suffix';
  }

  @override
  void dispose() {
    _selectedClientNotifier.dispose();
    _issueDateNotifier.dispose();
    _dueDateNotifier.dispose();
    _itemsNotifier.dispose();
    _isLoadingNotifier.dispose();
    _taxRateController.dispose();
    _discountController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _onSaveInvoice(BuildContext context, InvoicesCubit cubit) {
    FocusScope.of(context).unfocus();

    if (_selectedClientNotifier.value == null) {
      AppToast.show(
        context: context,
        title: AppStrings.pleaseSelectClient,
        type: ToastificationType.warning,
      );
      return;
    }

    final validItems = _itemsNotifier.value
        .where((item) => item.name.trim().isNotEmpty && item.quantity > 0)
        .toList();

    if (validItems.isEmpty) {
      AppToast.show(
        context: context,
        title: AppStrings.pleaseAddAtLeastOneItem,
        type: ToastificationType.warning,
      );
      return;
    }

    final subtotal = validItems.fold(0.0, (sum, item) => sum + item.totalPrice);
    final taxRate = double.tryParse(_taxRateController.text.trim()) ?? 0.0;
    final taxAmount = subtotal * (taxRate / 100);
    final discount = double.tryParse(_discountController.text.trim()) ?? 0.0;
    final grandTotal = (subtotal + taxAmount - discount).clamp(
      0.0,
      double.infinity,
    );

    _isLoadingNotifier.value = true;

    final invoice = InvoiceEntity(
      invoiceNumber: _autoGeneratedInvoiceNumber,
      client: _selectedClientNotifier.value!,
      items: validItems,
      issueDate: _issueDateNotifier.value,
      dueDate: _dueDateNotifier.value,
      subtotal: subtotal,
      taxRate: taxRate,
      taxAmount: taxAmount,
      discountAmount: discount,
      totalAmount: grandTotal,
      status: InvoiceStatus.draft,
      notes: _notesController.text.trim(),
    );

    cubit.createInvoice(invoice);
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;

    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (context) => getIt<ClientsCubit>()),
        BlocProvider(create: (context) => getIt<InvoicesCubit>()),
      ],
      child: CustomKeyboardUnfocus(
        child: Scaffold(
          appBar: CustomAppBar(
            title: AppStrings.createInvoice,
            showArrowBack: true,
          ),
          body: SafeArea(
            child: BlocConsumer<InvoicesCubit, InvoicesState>(
              listener: (context, state) {
                if (state is InvoiceActionSuccess) {
                  _isLoadingNotifier.value = false;
                  AppToast.show(
                    context: context,
                    title: state.message,
                    type: ToastificationType.success,
                  );
                  context.pop(true);
                } else if (state is InvoicesFailure) {
                  _isLoadingNotifier.value = false;
                  AppToast.show(
                    context: context,
                    title: state.error,
                    type: ToastificationType.error,
                  );
                }
              },
              builder: (context, state) {
                final invoicesCubit = context.read<InvoicesCubit>();

                return SingleChildScrollView(
                  padding: EdgeInsets.symmetric(
                    horizontal: 16.w,
                    vertical: 16.h,
                  ),
                  child: Form(
                    key: _formKey,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Auto-generated Invoice Number Badge
                        Container(
                          padding: EdgeInsets.symmetric(
                            horizontal: 14.w,
                            vertical: 10.h,
                          ),
                          decoration: BoxDecoration(
                            color: colors.primary.withValues(alpha: 0.08),
                            borderRadius: BorderRadius.circular(12.r),
                            border: Border.all(
                              color: colors.primary.withValues(alpha: 0.2),
                            ),
                          ),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(
                                AppStrings.invoiceNumber,
                                style: AppTextStyles.font13Regular.copyWith(
                                  color: colors.subText,
                                ),
                              ),
                              Text(
                                _autoGeneratedInvoiceNumber,
                                style: AppTextStyles.font14Bold.copyWith(
                                  color: colors.primary,
                                ),
                              ),
                            ],
                          ),
                        ),
                        Gap(16.h),

                        // Client Picker Section
                        ValueListenableBuilder<ClientEntity?>(
                          valueListenable: _selectedClientNotifier,
                          builder: (context, selectedClient, child) =>
                              InvoiceClientPicker(
                                selectedClient: selectedClient,
                                onClientSelected: (client) {
                                  _selectedClientNotifier.value = client;
                                },
                              ),
                        ),
                        Gap(16.h),

                        // Dates Section (Issue & Due Date)
                        InvoiceDatesSection(
                          issueDateNotifier: _issueDateNotifier,
                          dueDateNotifier: _dueDateNotifier,
                        ),
                        Gap(20.h),

                        // Invoice Items Section
                        ValueListenableBuilder<List<InvoiceItemEntity>>(
                          valueListenable: _itemsNotifier,
                          builder: (context, items, child) =>
                              InvoiceItemsSection(
                                items: items,
                                onAddItem: () {
                                  final current = List<InvoiceItemEntity>.from(
                                    items,
                                  );
                                  current.add(
                                    InvoiceItemEntity(
                                      itemId: DateTime.now()
                                          .millisecondsSinceEpoch
                                          .toString(),
                                      name: '',
                                      quantity: 1,
                                      unitPrice: 0,
                                    ),
                                  );
                                  _itemsNotifier.value = current;
                                },
                                onRemoveItem: (index) {
                                  final current = List<InvoiceItemEntity>.from(
                                    items,
                                  );
                                  current.removeAt(index);
                                  _itemsNotifier.value = current;
                                },
                                onUpdateItem: (index, updatedItem) {
                                  final current = List<InvoiceItemEntity>.from(
                                    items,
                                  );
                                  current[index] = updatedItem;
                                  _itemsNotifier.value = current;
                                },
                              ),
                        ),
                        Gap(20.h),

                        // Dynamic Calculations Summary
                        ValueListenableBuilder<List<InvoiceItemEntity>>(
                          valueListenable: _itemsNotifier,
                          builder: (context, items, child) {
                            final subtotal = items.fold(
                              0.0,
                              (sum, item) => sum + item.totalPrice,
                            );

                            return InvoiceCalculationSummary(
                              subtotal: subtotal,
                              taxRateController: _taxRateController,
                              discountController: _discountController,
                            );
                          },
                        ),
                        Gap(20.h),

                        // Optional Notes Section
                        TextFormFieldHelper(
                          controller: _notesController,
                          hint: AppStrings.notesHint,
                          maxLines: 3,
                          prefixIcon: Icon(
                            Icons.note_alt_outlined,
                            color: colors.subText,
                            size: 20.sp,
                          ),
                        ),
                        Gap(28.h),

                        // Create Invoice Button
                        ValueListenableBuilder<bool>(
                          valueListenable: _isLoadingNotifier,
                          builder: (context, isLoading, child) =>
                              CustomMaterialButton(
                                onPressed: () =>
                                    _onSaveInvoice(context, invoicesCubit),
                                text: AppStrings.createInvoice,
                                isLoading: isLoading,
                                maxWidth: true,
                                borderRadius: BorderRadius.circular(12.r),
                              ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
