// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
import 'core/env/env.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: Env.androidApiKey,
    appId: Env.androidAppId,
    messagingSenderId: Env.androidMessagingSenderId,
    projectId: Env.androidProjectId,
    storageBucket: Env.androidStorageBucket,
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.iosApiKey,
    appId: Env.iosAppId,
    messagingSenderId: Env.iosMessagingSenderId,
    projectId: Env.iosProjectId,
    storageBucket: Env.iosStorageBucket,
    iosBundleId: Env.iosBundleId,
  );
}
