import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:invoify/core/helpers/app_strings.dart';
import 'package:invoify/core/widgets/app_toasts.dart';
import 'package:invoify/core/widgets/custom_material_button.dart';
import 'package:invoify/features/clients/domain/entities/client_entity.dart';
import 'package:invoify/features/invoices/domain/entities/invoice_entity.dart';
import 'package:invoify/features/invoices/domain/entities/invoice_item_entity.dart';
import 'package:invoify/features/invoices/domain/enums/discount_type.dart';
import 'package:invoify/features/invoices/domain/enums/invoice_status.dart';
import 'package:invoify/features/invoices/presentation/view_models/invoices_cubit/invoices_cubit.dart';
import 'package:toastification/toastification.dart';

class AddEditInvoiceSaveButton extends StatelessWidget {
  const AddEditInvoiceSaveButton({
    super.key,
    this.existingInvoice,
    required this.isEditing,
    required this.autoGeneratedInvoiceNumber,
    required this.selectedClientNotifier,
    required this.itemsNotifier,
    required this.issueDateNotifier,
    required this.dueDateNotifier,
    required this.taxRateController,
    required this.discountController,
    required this.discountTypeNotifier,
    required this.notesController,
    required this.isLoadingNotifier,
  });

  final InvoiceEntity? existingInvoice;
  final bool isEditing;
  final String autoGeneratedInvoiceNumber;
  final ValueNotifier<ClientEntity?> selectedClientNotifier;
  final ValueNotifier<List<InvoiceItemEntity>> itemsNotifier;
  final ValueNotifier<DateTime> issueDateNotifier;
  final ValueNotifier<DateTime> dueDateNotifier;
  final TextEditingController taxRateController;
  final TextEditingController discountController;
  final ValueNotifier<DiscountType> discountTypeNotifier;
  final TextEditingController notesController;
  final ValueNotifier<bool> isLoadingNotifier;

  void _onSaveInvoice(BuildContext context) {
    FocusScope.of(context).unfocus();

    if (selectedClientNotifier.value == null) {
      AppToast.show(
        context: context,
        title: AppStrings.pleaseSelectClient,
        type: ToastificationType.warning,
      );
      return;
    }

    final validItems = itemsNotifier.value
        .where((item) => item.name.trim().isNotEmpty && item.quantity > 0)
        .toList();

    if (validItems.isEmpty) {
      AppToast.show(
        context: context,
        title: AppStrings.pleaseAddAtLeastOneItem,
        type: ToastificationType.warning,
      );
      return;
    }

    final cubit = context.read<InvoicesCubit>();
    final subtotal = validItems.fold(0.0, (sum, item) => sum + item.totalPrice);
    final taxRate = double.tryParse(taxRateController.text.trim()) ?? 0.0;
    final taxAmount = subtotal * (taxRate / 100);
    final discountInput =
        double.tryParse(discountController.text.trim()) ?? 0.0;
    final discountType = discountTypeNotifier.value;

    final double discountRate = discountType.isPercentage ? discountInput : 0.0;
    final double discountAmount = discountType.isPercentage
        ? subtotal * (discountInput / 100)
        : discountInput;

    final grandTotal = (subtotal + taxAmount - discountAmount).clamp(
      0.0,
      double.infinity,
    );

    isLoadingNotifier.value = true;

    final invoice = InvoiceEntity(
      invoiceId: existingInvoice?.invoiceId ?? '',
      userId: existingInvoice?.userId ?? '',
      invoiceNumber: autoGeneratedInvoiceNumber,
      client: selectedClientNotifier.value!,
      items: validItems,
      issueDate: issueDateNotifier.value,
      dueDate: dueDateNotifier.value,
      subtotal: subtotal,
      taxRate: taxRate,
      taxAmount: taxAmount,
      discountType: discountType,
      discountRate: discountRate,
      discountAmount: discountAmount,
      totalAmount: grandTotal,
      status: existingInvoice?.status ?? InvoiceStatus.draft,
      notes: notesController.text.trim(),
      createdAt: existingInvoice?.createdAt,
    );

    if (isEditing) {
      cubit.updateInvoice(invoice);
    } else {
      cubit.createInvoice(invoice);
    }
  }

  @override
  Widget build(BuildContext context) => ValueListenableBuilder<bool>(
    valueListenable: isLoadingNotifier,
    builder: (context, isLoading, child) => CustomMaterialButton(
      onPressed: () => _onSaveInvoice(context),
      text: isEditing ? AppStrings.saveChanges : AppStrings.createInvoice,
      isLoading: isLoading,
      maxWidth: true,
      borderRadius: BorderRadius.circular(12.r),
    ),
  );
}
